### ISSUE TITLE
[Suggestion] Inferno Plugin - Fix false prayer identification

### ISSUE THREAD

**Issue by willediger** [xKylee/plugins-source#109]
When leaving an engagement with an NPC and safespotting it, the plugin thinks we're still in their aggro for 1 attack, unnecessarily. This leads to suggesting prayers which do not need to be prayed. I most notice this with blobs because their attack sequence is longer, but it also happens with rangers/magers.

**Comment by xKylee** [comment]
@willediger any chance you could get a gif pls?
