### ISSUE TITLE
ticktimers: Hopping and toggling the plugin doesn't clear the NPC-list

### ISSUE THREAD

**Issue by Im2be** [xKylee/plugins-source#145]
**Issue:** 

- When hopping at a GWD door, the NPC's don't get removed from the list

- As far as I can see in the code, toggling the plugin doesn't remove or add any NPC's in the list (which has caused me to crash on one occasion when relogging without exiting the client)

**How to reproduce:** 

- Try hopping at bandos GWD with the appropriate config and you get the result in this [screenshot](https://imgur.com/a/0WOjLdb)

- I'm not 100% sure how to reproduce and view the second issue, it's only happened to me once. Though just logging the NPC-list item count every tick will reveal a memory leak.

**Comment by xKylee** [comment]
fixed in #149.
