### ISSUE TITLE
Suggestion:  Can we add a no ghost timer to the cerberus plugin

### ISSUE THREAD

**Issue by JustDelete** [xKylee/plugins-source#191]
Pls check youtube video for what I mean, he also has a Github but cannot ad o OPENOSRS:
https://www.youtube.com/watch?v=tuUqnAXeWqo

**Comment by xKylee** [comment]
If you can get accurate timings on when the timer should start, exactly how long it should last for etc then it’s something we can add.

**Comment by JustDelete** [comment]
After you hit cerberus once a countdown of 56sec when ends a ring sound, that's it

**Comment by xKylee** [comment]
There are other variables though.

Cerb has to be above 400hp
There is also another ~50 seconds you have to kill cerb otherwise ghosts spawn
Time to stop attacking etc.

**Comment by dutta64** [comment]
Is the timer affected if you stand under him? I recall there being a pastebin somewhere that shows the attack pattern... last time I used the plugin it showed upcoming attacks and when to stop to avoid ghosts.

**Comment by JustDelete** [comment]
I didn't want to make it hard, because I am watching the hp my self etc.
I thought that a timer of 56sec should be enough after the first hit

**Comment by xKylee** [comment]
If you’re literally just after a timer, why not just use his one? If you’re going to “not want” the proper logic then there is 0 point adding this

**Comment by JustDelete** [comment]
I tried to add the timer to the plugin like on the video, but I cannot add this.
Superman told me to suggest it.

But maybe it's a smart idea to add everything for other people.

-After first hit countdown of 56sec
-Hit till around 400hp+- maybe with a warning
-After 56sec you can hit the boss again
-50secs to kill the boss again
