### ISSUE TITLE
Inventory Setups bugging out all the time

### ISSUE THREAD

**Issue by thhdragon** [xKylee/plugins-source#250]
my inventory setup keeps going buggy lately, not filtering my bank and plugin not recognizing im wearing the gear or have an item in the right space (shows the red highlighted square like its wrong). im constantly having to uninstall and reinstall it to get it temporarily working again, i can get a log if it will help

**Comment by dutta64** [comment]
That plugin is a part of this https://github.com/Owain94/OpenOSRS-RL-hub repo I believe. Which, as far as I know, is ported from RuneLite.
