### ISSUE TITLE
[Suggestion] Effect Timers - Add an option to show the timers in a tab

### ISSUE THREAD

**Issue by Levy2** [xKylee/plugins-source#275]
Right now the timers show up right on the other players. It would be nice if there was an option that would add a tab to the OpenOSRS sidebar in which a table is shown with names and all of the timers which are enabled. This way there is no visible effect timers on the play area.

**Comment by xKylee** [comment]
no

**Comment by tomcylke** [comment]
This is actually a decent idea it's just annoying to implement
