### ISSUE TITLE
Can't add to OpenOSRS

### ISSUE THREAD

**Issue by Aholicknight** [xKylee/plugins-source#440]
I am sorry for this being a stupid issue but for some reason, I can't add it into OpenOSRS.

https://user-images.githubusercontent.com/7843719/133633371-ef41d5b5-3f20-4480-ada8-d9f36b4f1a55.mp4

How can I fix this? Thanks.

**Comment by grian32** [comment]
plugins-release not plugins-source

**Comment by Aholicknight** [comment]
![image](https://user-images.githubusercontent.com/7843719/133639141-da2298a3-6334-4b86-9d70-c9c12a9a47c4.png)
Yup, that works, thank you!
