### ISSUE TITLE
Blackjack not working

### ISSUE THREAD

**Issue by Desuuuuuu** [xKylee/plugins-source#446]
Blackjack not working

**Comment by emiljensen2** [comment]
If your blackjack isn't working try this:
Blackjacking is kinda bugged, you may have to turn on "Always right-click on NPC" in-game, then try turning the plugin off and on. 
Make sure "Menu Entry Swapper" is on as well..
Make sure you don't have the blackjack plugin from pluginhub installed
https://imgur.com/spqVdBy
