### ISSUE TITLE
MenuEntrySwapperExtended bugs

### ISSUE THREAD

**Issue by PaulVlahosCS** [xKylee/plugins-source#49]
Title is vague because the bug is more of an all encompassing crashing/stopping of function of the plugin.

This error is thrown: https://paste.ee/p/FjIRF

Then the plugin stops functioning altogether. Whatever swaps it had swapped stay as they were and cannot be changed until a restart. I assume this meaning the plugin itself has stopped functioning. Seems to be an issue with unfocusing and focusing of the client causing stopHotkey to throw the error?

https://gfycat.com/messyheartfeltagouti

**Comment by xKylee** [comment]
This isn’t a code issue, it’s an issue with rxjava.

Please ensure mesextended is up to date and so is your client; the issue looks to be a compatibility issue between rx3 and rx2
