### ISSUE TITLE
[suggestion] weapon attack cooldown timer

### ISSUE THREAD

**Issue by noiseexplosion** [xKylee/plugins-source#55]
just a simple timer, maybe over your head or something that tells you how many ticks are left until you can attack again. would be useful at raids 1&2 and maybe pking? apologies if this has been requested before

**Comment by tomcylke** [comment]
This is actually absurdly complicated to implement. It needs to handle the 3 tick delay for eating/potting + a bunch of other stuff. The metronome plugin lets you count ticks manually, which is the next best thing.

**Comment by xKylee** [comment]
as tom said, whilst possible its going to be a PITA. it would also be extremely flakey due to being able to 1 tick, pot tricking, tick manipulation etc. this isnt something i will implement.
