### ISSUE TITLE
[Suggestion] Shift-click fill rune essence pouch

### ISSUE THREAD

**Issue by OSRS-Nick** [xKylee/plugins-source#73]
Ourania altar runecrafting requires me to right click fill pouches with essence when I'd rather just shift-left click the pouches. I think menu entry swapper has "empty" has the left click default option. 

Would also be cool if left click "fill" was turned on when you are say within 10 squares of enolia (the banker)?

**Comment by xKylee** [comment]
Turn on runecrafting plugin, you can already left click fill/empty
